spring:
  profiles:
    active: dev # 默认激活开发环境
  config:
    import:
      - optional:classpath:mysql.yaml
      - optional:classpath:redis.yaml
      - optional:classpath:mail.yaml
      - optional:classpath:alipay.yaml
      - optional:classpath:mq.yaml
      - optional:classpath:system.yaml
